### ISSUE TITLE
Won't compile on Teensy 4.1 using 'basic usage' example. Here is the error.

### ISSUE THREAD

**Issue by mbueno0** [Chris--A/PrintEx#42]
Arduino: 1.8.19 (Windows 10), TD: 1.56, Board: "Teensy 4.1, Serial, 600 MHz, Faster, US English"

In file included from C:\Users\mbuen\Documents\Arduino\libraries\PrintEx\src/lib/PrintVariadic.h:24:0,

                 from C:\Users\mbuen\Documents\Arduino\libraries\PrintEx\src/lib/PrintExtension.h:43,

                 from C:\Users\mbuen\Documents\Arduino\libraries\PrintEx\src/lib/MemoryPrinter.h:25,

                 from C:\Users\mbuen\Documents\Arduino\libraries\PrintEx\src/PrintEx.h:26,

                 from C:\Users\mbuen\Documents\Arduino\printEx_test\printEx_test.ino:8:

C:\Users\mbuen\Documents\Arduino\libraries\PrintEx\src/lib/TypeTraits.h:78:55: error: 'template<bool V, class T, class U> struct select' redeclared as different kind of symbol

     template< bool V, typename T, typename U > struct select { typedef U type; };

                                                       ^

In file included from c:\program files (x86)\arduino_1.8.19\hardware\tools\arm\arm-none-eabi\include\sys\types.h:68:0,

                 from c:\program files (x86)\arduino_1.8.19\hardware\tools\arm\arm-none-eabi\include\stdio.h:61,

                 from C:\Program Files (x86)\arduino_1.8.19\hardware\teensy\avr\cores\teensy4/Print.h:35,

                 from C:\Program Files (x86)\arduino_1.8.19\hardware\teensy\avr\cores\teensy4/Stream.h:24,

                 from C:\Program Files (x86)\arduino_1.8.19\hardware\teensy\avr\cores\teensy4/HardwareSerial.h:115,

                 from C:\Program Files (x86)\arduino_1.8.19\hardware\teensy\avr\cores\teensy4/WProgram.h:46,

                 from C:\Users\mbuen\AppData\Local\Temp\arduino_build_646814\pch\Arduino.h:6:

c:\program files (x86)\arduino_1.8.19\hardware\tools\arm\arm-none-eabi\include\sys\select.h:73:5: note: previous declaration 'int select(int, _types_fd_set*, _types_fd_set*, _types_fd_set*, timeval*)'

 int select __P ((int __n, fd_set *__readfds, fd_set *__writefds,

     ^

In file included from C:\Users\mbuen\Documents\Arduino\libraries\PrintEx\src/lib/PrintVariadic.h:24:0,

                 from C:\Users\mbuen\Documents\Arduino\libraries\PrintEx\src/lib/PrintExtension.h:43,

                 from C:\Users\mbuen\Documents\Arduino\libraries\PrintEx\src/lib/MemoryPrinter.h:25,

                 from C:\Users\mbuen\Documents\Arduino\libraries\PrintEx\src/PrintEx.h:26,

                 from C:\Users\mbuen\Documents\Arduino\printEx_test\printEx_test.ino:8:

C:\Users\mbuen\Documents\Arduino\libraries\PrintEx\src/lib/TypeTraits.h:79:46: error: 'select' is not a class template

     template<typename T, typename U > struct select<true,T,U>{ typedef T type; };

                                              ^

C:\Users\mbuen\Documents\Arduino\libraries\PrintEx\src/lib/TypeTraits.h:79:61: error: 'template<class T, class U> struct select' redeclared as different kind of symbol

     template<typename T, typename U > struct select<true,T,U>{ typedef T type; };

                                                             ^

In file included from c:\program files (x86)\arduino_1.8.19\hardware\tools\arm\arm-none-eabi\include\sys\types.h:68:0,

                 from c:\program files (x86)\arduino_1.8.19\hardware\tools\arm\arm-none-eabi\include\stdio.h:61,

                 from C:\Program Files (x86)\arduino_1.8.19\hardware\teensy\avr\cores\teensy4/Print.h:35,

                 from C:\Program Files (x86)\arduino_1.8.19\hardware\teensy\avr\cores\teensy4/Stream.h:24,

                 from C:\Program Files (x86)\arduino_1.8.19\hardware\teensy\avr\cores\teensy4/HardwareSerial.h:115,

                 from C:\Program Files (x86)\arduino_1.8.19\hardware\teensy\avr\cores\teensy4/WProgram.h:46,

                 from C:\Users\mbuen\AppData\Local\Temp\arduino_build_646814\pch\Arduino.h:6:

c:\program files (x86)\arduino_1.8.19\hardware\tools\arm\arm-none-eabi\include\sys\select.h:73:5: note: previous declaration 'int select(int, _types_fd_set*, _types_fd_set*, _types_fd_set*, timeval*)'

 int select __P ((int __n, fd_set *__readfds, fd_set *__writefds,

     ^

Error compiling for board Teensy 4.1.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
